# Generated by Django 4.2.7 on 2023-12-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('sala', models.CharField(choices=[('roja', 'Roja'), ('amarilla', 'Amarilla'), ('azul', 'Azul'), ('verde', 'Verde')], default='azul', max_length=15)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['usuario', '-fechaPublicacion'],
            },
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
