# Generated by Django 4.2.7 on 2023-12-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_novedad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
