# Generated by Django 4.2.7 on 2023-12-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0005_alter_novedad_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='usuario',
            field=models.CharField(max_length=200),
        ),
    ]
