# Generated by Django 4.2.7 on 2023-12-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0007_alter_novedad_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novedad',
            options={'ordering': ['fechaPublicacion', 'usuario']},
        ),
    ]
