# Generated by Django 4.2.7 on 2023-12-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0008_alter_novedad_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='remitente',
            field=models.CharField(default='familia', max_length=255),
        ),
    ]
