# Generated by Django 5.0 on 2023-12-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0009_novedad_remitente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='remitente',
            field=models.CharField(default='Familia', max_length=255),
        ),
    ]
